services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data-office-forms
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
