import { fr } from "@codegouvfr/react-dsfr";
import type { ReferenceData } from "@prisma/client";
import { createColumnHelper } from "@tanstack/react-table";
import Head from "next/head";
import { useState } from "react";
import DsfrTable from "~/components/DsfrTable";
import { api } from "~/utils/api";

type ReferenceDataForTable = ReferenceData & { requestCount: number };

const columnHelper = createColumnHelper<ReferenceDataForTable>();

const columns = [
	columnHelper.accessor("id", {
		header: "ID",
		cell: (info) => info.getValue(),
	}),
	columnHelper.accessor("name", {
		header: "Nom",
		cell: (info) => info.getValue(),
	}),
	columnHelper.accessor("createdAt", {
		header: "Date de création",
		cell: (info) => info.getValue().toLocaleDateString(),
	}),
	columnHelper.accessor("updatedAt", {
		header: "Date de mise à jour",
		cell: (info) => info.getValue().toLocaleDateString(),
	}),
	columnHelper.accessor("requestCount", {
		header: "Nombre de demandes",
		cell: (info) => info.getValue(),
	}),
];

const numberPerPage = 10;

export default function AdminHome() {
	const [currentPage, setCurrentPage] = useState(1);

	const { data: totalCount } = api.reference.getCount.useQuery(undefined, {
		initialData: 0,
	});

	const { data } = api.reference.getList.useQuery({
		page: currentPage,
		numberPerPage,
	});

	return (
		<>
			<Head>
				<title>DCF - Admin</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className={fr.cx("fr-mt-4w")}>
					<h1>Liste des références</h1>
				</div>
				<DsfrTable<ReferenceDataForTable>
					data={data ?? []}
					columns={columns}
					totalCount={totalCount}
					pagination={{
						numberPerPage,
						currentPage,
						setCurrentPage,
					}}
				/>
			</main>
		</>
	);
}
