import Head from "next/head";
import { fr } from "@codegouvfr/react-dsfr";
import { api } from "~/utils/api";
import { createColumnHelper } from "@tanstack/react-table";
import type { User } from "@prisma/client";
import DsfrTable from "~/components/DsfrTable";

type UserForTable = Pick<User, "id" | "email" | "name">;

const columnHelper = createColumnHelper<UserForTable>();

const columns = [
	columnHelper.accessor("id", {
		header: "ID",
		cell: (info) => info.getValue(),
	}),
	columnHelper.accessor("email", {
		header: "Email",
		cell: (info) => info.getValue(),
	}),
	columnHelper.accessor("name", {
		header: "Nom",
		cell: (info) => info.getValue(),
	}),
];

const fallbackData: UserForTable[] = [];

export default function AdminHome() {
	const { data } = api.user.getAll.useQuery();

	return (
		<>
			<Head>
				<title>DCF - Admin</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className={fr.cx("fr-mt-4w")}>
					<h1>Liste des utilisateurs</h1>
				</div>
				<DsfrTable<UserForTable>
					data={data ?? fallbackData}
					columns={columns}
				/>
			</main>
		</>
	);
}
