import { fr } from "@codegouvfr/react-dsfr";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>DCF - Accueil</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className={fr.cx("fr-mt-4w", "fr-mb-8w")}>
					<h1>Data Office - Data Contract Formulaire</h1>
				</div>
			</main>
		</>
	);
}
