import Head from "next/head";
import { fr } from "@codegouvfr/react-dsfr";
import { tss } from "tss-react";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.request.getAll.useQuery();

  const { classes } = useStyles();
  return (
    <>
      <Head>
        <title>DCF - Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={fr.cx("fr-mt-4w", "fr-mb-8w")}>
          <h1>Liste des demandes</h1>
        </div>
      </main>
    </>
  );
}

const useStyles = tss.withName(Home.name).create(() => ({
  formWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: fr.spacing("3w"),
  },
}));
